name: travel_nepal
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-174.3.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  get_storage: ^2.1.1
  oktoast: ^3.4.0
  connectivity_plus: ^5.0.2
  flutter_screenutil: ^5.9.0
  intl:
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  auto_route: ^7.8.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  bloc: ^8.1.2
  injectable: ^2.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  chewie: ^1.7.4
  video_player: ^2.8.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  mocktail:
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - asset/onboarding/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
